# Generated by Django 3.2.3 on 2021-05-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieude', models.CharField(blank=True, max_length=255, null=True)),
                ('hinh', models.CharField(max_length=255)),
            ],
        ),
    ]
