# Generated by Django 3.2.3 on 2021-05-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sochuong', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sach',
            name='chuong',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ChitietSach.chuong'),
        ),
    ]
