# Generated by Django 3.2.3 on 2021-05-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0005_alter_sach_hinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='ngaydang',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
