# Generated by Django 3.2.3 on 2021-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0006_sach_ngaydang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='hinh',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
