# Generated by Django 3.2.3 on 2021-05-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0007_alter_sach_hinh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sach',
            old_name='noidung',
            new_name='mota',
        ),
        migrations.AddField(
            model_name='chuong',
            name='noidung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
