# Generated by Django 3.2.3 on 2021-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0008_auto_20210519_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='danhmuc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='tacgia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='theloai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Danhmuc',
        ),
        migrations.DeleteModel(
            name='Tacgia',
        ),
        migrations.DeleteModel(
            name='Theloai',
        ),
    ]
