# Generated by Django 3.2.3 on 2021-05-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
