# Generated by Django 3.2.3 on 2021-05-24 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0012_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sach',
            name='chuong',
        ),
        migrations.AddField(
            model_name='chuong',
            name='tieude',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ChitietSach.sach'),
        ),
    ]
