# Generated by Django 3.2.3 on 2021-05-28 08:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChitietSach', '0016_auto_20210527_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
