# Generated by Django 3.2.3 on 2021-05-28 09:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0017_sach_favourites'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sach',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
