# Generated by Django 3.2.3 on 2021-05-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0018_alter_sach_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='danhmuc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.danhmuc'),
        ),
        migrations.AlterField(
            model_name='sach',
            name='theloai',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.theloai'),
        ),
    ]
