# Generated by Django 3.2.3 on 2021-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0019_auto_20210529_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='danhmuc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sach',
            name='theloai',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
