# Generated by Django 3.2.3 on 2021-05-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0020_auto_20210529_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='danhmuc',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.danhmuc'),
        ),
        migrations.AlterField(
            model_name='sach',
            name='theloai',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.theloai'),
        ),
    ]
