# Generated by Django 3.2.3 on 2021-05-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0021_auto_20210529_1942'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sach',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='sach',
            name='favourites',
        ),
    ]
