# Generated by Django 3.1.7 on 2021-05-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChitietSach', '0024_auto_20210530_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sach',
            name='danhmuc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.danhmuc'),
        ),
        migrations.AlterField(
            model_name='sach',
            name='theloai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ChitietSach.theloai'),
        ),
    ]
